"""
Functions around machine learning

for keras
"""

try:
    import matplotlib
    matplotlib.use('tkagg')
    import matplotlib.pyplot as plt
except:
    plt = None

from ._exception import *
        
def plot_keras_history(
    history,
    save=True,
    filename='keras_history.png'
):
    '''
    keras history plotter

    argument :
        history : keras.callbacks.callbacks.History()
            History object
            the returning object of fit() in every model
            generated by Keras.
        save : boolean (default : True)
            if true, save image
        filename : str (default : 'keras_history.png')
            the name of the file when saving
    '''

    if not plt:
        raise_no_module_error('matplotlib')

    plt.figure(figsize=(12, 5))
    plt.subplot(1, 2, 1)
    plt.plot(history.history['accuracy'])
    plt.plot(history.history['val_accuracy'])
    plt.title('model accuracy')
    plt.xlabel('epoch')
    plt.ylabel('accuracy')
    plt.legend(['acc', 'val_acc'], loc='upper left')

    plt.subplot(1, 2, 2)
    plt.plot(history.history['loss'])
    plt.plot(history.history['val_loss'])
    plt.title('model loss')
    plt.xlabel('epoch')
    plt.ylabel('loss')
    plt.legend(['loss', 'val_loss'], loc='upper left')

    if save:
        plt.savefig(filename)
    plt.show()
